coverage:
  range: '60...100'
  precision: 2
  status:
    default:
      enabled: yes
      target: 90
      threshold: 2
    patch:
      default:
        enabled: no
        if_not_found: success

comment:
  layout: "header, diff, changes, tree"
  behavior: default